version: 1
labels:
  - label: "auto-risky"
    size-above: 300
    files:
      - ".*?/src/main/java/.*"
  - label: "db-changes"
    files:
      - ".*/db/changelog/.*"
      - ".*/db.changelog/.*"
      - ".*/db*changelog/.*"
  - label: "ta-fe-company"
    files:
      - "apps/ta-fe-company/.*"
      - "libs/.*"
  - label: "ta-fe-user"
    files:
      - "apps/ta-fe-user/.*"
      - "apps/ta-fe-user-e2e/.*"
      - "libs/.*"
      - "package.json"
      - "package-lock.json"
  - label: "ta-fe-team-event"
    files:
      - "apps/team-event/.*"
      - "libs/.*"
  - label: "ta-fe-helpcenter"
    files:
      - "apps/ta-fe-helpcenter/.*"
      - "libs/.*"